services:
  - type: web
    name: saywhat-sirtis
    env: node
    runtime: node
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /api/test/hello
    autoDeploy: true
    region: oregon
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: "https://sirtis-saywhat.onrender.com"
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgres://postgres.yuwwqupyqpmkbqzvqiee:8FNI4OdtFINUw2GL@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"
      - key: DIRECT_URL
        value: "postgres://postgres.yuwwqupyqpmkbqzvqiee:8FNI4OdtFINUw2GL@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"
