services:
  - type: web
    name: saywhat-sirtis
    env: node
    runtime: node
    buildCommand: npm ci --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: next start -H 0.0.0.0 -p $PORT
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: "https://sirtis-saywhat.onrender.com"
      - key: NEXTAUTH_SECRET
        value: "6a1f9c25c069957affc22548e3fb186f86caf4dc8005f1148a18b1d9fa912744"
      - key: DATABASE_URL
        value: "postgres://postgres.yuwwqupyqpmkbqzvqiee:8FNI4OdtFINUw2GL@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: DIRECT_URL
        value: "postgres://postgres.yuwwqupyqpmkbqzvqiee:8FNI4OdtFINUw2GL@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: SUPABASE_URL
        value: "https://yuwwqupyqpmkbqzvqiee.supabase.co"
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
