services:
  - type: web
    name: sirtis-web
    env: node
    buildCommand: npm run render:deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false
    autoDeploy: true
    region: oregon
    plan: starter
    
databases:
  - name: sirtis-db
    databaseName: sirtis_production
    user: sirtis_admin
    plan: starter
