-- Add Sample Assets SQL
INSERT INTO assets (
  id, "assetTag", name, description, category, brand, model, "serialNumber", 
  "purchaseDate", "purchasePrice", "currentValue", location, condition, status, 
  "createdAt", "updatedAt"
) VALUES
  (
    'ast-001-' || extract(epoch from now())::text,
    'AST-001',
    'Dell Laptop OptiPlex 7090',
    'Dell business laptop for office use',
    'Computer',
    'Dell',
    'OptiPlex 7090',
    'DL789123456',
    '2023-01-15'::date,
    1200.00,
    900.00,
    'IT Department',
    'GOOD',
    'ACTIVE',
    now(),
    now()
  ),
  (
    'ast-002-' || extract(epoch from now())::text,
    'AST-002',
    'HP LaserJet Pro 404dn',
    'Office printer for document printing',
    'Equipment',
    'HP',
    'LaserJet Pro 404dn',
    'HP404789123',
    '2023-03-20'::date,
    350.00,
    280.00,
    'Admin Office',
    'EXCELLENT',
    'ACTIVE',
    now(),
    now()
  ),
  (
    'ast-003-' || extract(epoch from now())::text,
    'AST-003',
    'Office Desk Wooden',
    'Standard office desk with drawers',
    'Furniture',
    'IKEA',
    'BEKANT',
    'IK160800',
    '2022-11-10'::date,
    180.00,
    120.00,
    'Office Floor 2',
    'GOOD',
    'ACTIVE',
    now(),
    now()
  ),
  (
    'ast-004-' || extract(epoch from now())::text,
    'AST-004',
    'Toyota Hiace Van',
    'Company vehicle for field operations',
    'Vehicle',
    'Toyota',
    'Hiace',
    'TY2023HIACE789',
    '2023-06-01'::date,
    35000.00,
    32000.00,
    'Vehicle Fleet',
    'EXCELLENT',
    'ACTIVE',
    now(),
    now()
  ),
  (
    'ast-005-' || extract(epoch from now())::text,
    'AST-005',
    'Samsung Monitor 27"',
    '27-inch 4K monitor for design work',
    'Computer',
    'Samsung',
    'M7 27"',
    'SM27M7789123',
    '2023-08-15'::date,
    450.00,
    380.00,
    'Design Department',
    'EXCELLENT',
    'ACTIVE',
    now(),
    now()
  )
ON CONFLICT ("assetTag") DO NOTHING;
