import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import ExcelJS from 'exceljs';

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const template = searchParams.get('template') || 'comprehensive';
    const period = searchParams.get('period') || '12months';
    const departmentFilter = searchParams.get('department') || 'all';
    const format = searchParams.get('format') || 'xlsx';

    // Calculate date range
    const now = new Date();
    const startDate = new Date();
    
    if (period !== 'all') {
      switch (period) {
        case '1month':
          startDate.setMonth(now.getMonth() - 1);
          break;
        case '3months':
          startDate.setMonth(now.getMonth() - 3);
          break;
        case '6months':
          startDate.setMonth(now.getMonth() - 6);
          break;
        case '24months':
          startDate.setFullYear(now.getFullYear() - 2);
          break;
        default:
          startDate.setFullYear(now.getFullYear() - 1);
      }
    } else {
      startDate.setFullYear(2000, 0, 1); // All time
    }

    const baseFilter: any = {
      isDeleted: false,
      isPersonalRepo: false,
      createdAt: period !== 'all' ? { gte: startDate } : undefined
    };

    if (departmentFilter !== 'all') {
      baseFilter.department = departmentFilter;
    }

    // Fetch comprehensive data
    const documents = await prisma.documents.findMany({
      where: baseFilter,
      select: {
        id: true,
        originalName: true,
        filename: true,
        category: true,
        classification: true,
        size: true,
        department: true,
        uploadedBy: true,
        viewCount: true,
        downloadCount: true,
        createdAt: true,
        updatedAt: true,
        tags: true,
        folderPath: true
      },
      orderBy: { createdAt: 'desc' }
    });

    if (format === 'xlsx') {
      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'SAYWHAT SIRTIS Document Repository';
      workbook.created = new Date();
      workbook.modified = new Date();

      // Create sheets based on template
      if (template === 'comprehensive' || template === 'category-summary') {
        // Summary Sheet
        const summarySheet = workbook.addWorksheet('Summary', {
          properties: { tabColor: { argb: 'FFf97316' } }
        });
        
        const totalSize = documents.reduce((sum, doc) => sum + doc.size, 0);
        const totalViews = documents.reduce((sum, doc) => sum + (doc.viewCount || 0), 0);
        const totalDownloads = documents.reduce((sum, doc) => sum + (doc.downloadCount || 0), 0);

        summarySheet.columns = [
          { header: 'Metric', key: 'metric', width: 35 },
          { header: 'Value', key: 'value', width: 25 }
        ];

        summarySheet.addRows([
          { metric: 'Report Title', value: `Document Repository ${template.replace('-', ' ').toUpperCase()} Report` },
          { metric: 'Generated On', value: new Date().toLocaleString() },
          { metric: 'Generated By', value: session.user.name || session.user.email || 'Unknown' },
          { metric: 'Period', value: period === 'all' ? 'All Time' : period.replace('months', ' Months').replace('month', ' Month') },
          { metric: 'Department Filter', value: departmentFilter === 'all' ? 'All Departments' : departmentFilter },
          { metric: '', value: '' },
          { metric: '📊 KEY METRICS', value: '' },
          { metric: 'Total Documents', value: documents.length.toLocaleString() },
          { metric: 'Total Storage (GB)', value: (totalSize / 1024 / 1024 / 1024).toFixed(2) },
          { metric: 'Average File Size (MB)', value: documents.length > 0 ? ((totalSize / documents.length) / 1024 / 1024).toFixed(2) : '0' },
          { metric: 'Total Views', value: totalViews.toLocaleString() },
          { metric: 'Total Downloads', value: totalDownloads.toLocaleString() },
          { metric: 'Engagement Rate (%)', value: documents.length > 0 ? ((totalViews / documents.length) * 100).toFixed(1) : '0' }
        ]);

        // Style header
        summarySheet.getRow(1).font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
        summarySheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
        summarySheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'center' };

        // Style key sections
        summarySheet.getRow(7).font = { bold: true, size: 11 };
        summarySheet.getRow(7).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFfed7aa' }
        };
      }

      if (template === 'comprehensive' || template === 'category-summary') {
        // Categories Sheet
        const categoryGroups = await prisma.documents.groupBy({
          by: ['category'],
          where: baseFilter,
          _count: { category: true },
          _sum: { size: true, viewCount: true, downloadCount: true }
        });

        const categoriesSheet = workbook.addWorksheet('Categories');
        categoriesSheet.columns = [
          { header: 'Category', key: 'category', width: 30 },
          { header: 'Document Count', key: 'count', width: 18 },
          { header: 'Total Size (MB)', key: 'size', width: 18 },
          { header: 'Avg Size (MB)', key: 'avgSize', width: 15 },
          { header: 'Total Views', key: 'views', width: 15 },
          { header: 'Total Downloads', key: 'downloads', width: 18 },
          { header: 'Percentage', key: 'percentage', width: 12 }
        ];

        categoriesSheet.addRows(
          categoryGroups.map(group => {
            const count = group._count.category;
            const size = (group._sum.size || 0) / 1024 / 1024;
            return {
              category: group.category || 'OTHER',
              count,
              size: size.toFixed(2),
              avgSize: count > 0 ? (size / count).toFixed(2) : '0',
              views: group._sum.viewCount || 0,
              downloads: group._sum.downloadCount || 0,
              percentage: documents.length > 0 ? ((count / documents.length) * 100).toFixed(1) + '%' : '0%'
            };
          })
        );

        categoriesSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
        categoriesSheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
      }

      if (template === 'comprehensive' || template === 'department-analysis') {
        // Departments Sheet
        const departmentGroups = await prisma.documents.groupBy({
          by: ['department'],
          where: baseFilter,
          _count: { department: true },
          _sum: { size: true, viewCount: true, downloadCount: true }
        });

        const departmentsSheet = workbook.addWorksheet('Departments');
        departmentsSheet.columns = [
          { header: 'Department', key: 'department', width: 35 },
          { header: 'Document Count', key: 'count', width: 18 },
          { header: 'Total Size (MB)', key: 'size', width: 18 },
          { header: 'Total Views', key: 'views', width: 15 },
          { header: 'Total Downloads', key: 'downloads', width: 18 },
          { header: 'Active Users', key: 'users', width: 15 }
        ];

        const departmentRows = await Promise.all(
          departmentGroups.map(async (group) => {
            const dept = group.department || 'Unknown';
            const uniqueUploaders = await prisma.documents.findMany({
              where: { ...baseFilter, department: dept },
              select: { uploadedBy: true },
              distinct: ['uploadedBy']
            });

            return {
              department: dept,
              count: group._count.department,
              size: ((group._sum.size || 0) / 1024 / 1024).toFixed(2),
              views: group._sum.viewCount || 0,
              downloads: group._sum.downloadCount || 0,
              users: uniqueUploaders.length
            };
          })
        );

        departmentsSheet.addRows(departmentRows);

        departmentsSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
        departmentsSheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
      }

      if (template === 'comprehensive' || template === 'security-audit') {
        // Security Sheet
        const securityGroups = await prisma.documents.groupBy({
          by: ['classification'],
          where: baseFilter,
          _count: { classification: true },
          _sum: { size: true }
        });

        const securitySheet = workbook.addWorksheet('Security Classifications');
        securitySheet.columns = [
          { header: 'Classification', key: 'classification', width: 25 },
          { header: 'Document Count', key: 'count', width: 18 },
          { header: 'Total Size (MB)', key: 'size', width: 18 },
          { header: 'Percentage', key: 'percentage', width: 12 }
        ];

        securitySheet.addRows(
          securityGroups.map(group => ({
            classification: group.classification || 'PUBLIC',
            count: group._count.classification,
            size: ((group._sum.size || 0) / 1024 / 1024).toFixed(2),
            percentage: documents.length > 0 ? ((group._count.classification / documents.length) * 100).toFixed(1) + '%' : '0%'
          }))
        );

        securitySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
        securitySheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
      }

      if (template === 'comprehensive' || template === 'activity-report') {
        // User Activity Sheet
        const userGroups = await prisma.documents.groupBy({
          by: ['uploadedBy'],
          where: baseFilter,
          _count: { uploadedBy: true },
          _sum: { viewCount: true, downloadCount: true }
        });

        const activitySheet = workbook.addWorksheet('User Activity');
        activitySheet.columns = [
          { header: 'User', key: 'user', width: 35 },
          { header: 'Uploads', key: 'uploads', width: 12 },
          { header: 'Total Views', key: 'views', width: 15 },
          { header: 'Total Downloads', key: 'downloads', width: 18 },
          { header: 'Activity Score', key: 'score', width: 15 }
        ];

        activitySheet.addRows(
          userGroups.map(group => {
            const uploads = group._count.uploadedBy;
            const views = group._sum.viewCount || 0;
            const downloads = group._sum.downloadCount || 0;
            return {
              user: group.uploadedBy || 'Unknown',
              uploads,
              views,
              downloads,
              score: uploads + views + downloads
            };
          }).sort((a, b) => b.score - a.score)
        );

        activitySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
        activitySheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
      }

      // All Documents Sheet (for comprehensive report)
      if (template === 'comprehensive') {
        const docsSheet = workbook.addWorksheet('All Documents');
        docsSheet.columns = [
          { header: 'File Name', key: 'name', width: 45 },
          { header: 'Category', key: 'category', width: 20 },
          { header: 'Classification', key: 'classification', width: 15 },
          { header: 'Size (MB)', key: 'size', width: 12 },
          { header: 'Department', key: 'department', width: 30 },
          { header: 'Uploaded By', key: 'uploadedBy', width: 25 },
          { header: 'Views', key: 'views', width: 10 },
          { header: 'Downloads', key: 'downloads', width: 12 },
          { header: 'Upload Date', key: 'created', width: 18 },
          { header: 'Folder Path', key: 'folder', width: 40 }
        ];

        docsSheet.addRows(
          documents.slice(0, 1000).map(doc => ({ // Limit to 1000 for performance
            name: doc.originalName,
            category: doc.category || 'OTHER',
            classification: doc.classification || 'PUBLIC',
            size: (doc.size / 1024 / 1024).toFixed(2),
            department: doc.department || 'Unknown',
            uploadedBy: doc.uploadedBy || 'Unknown',
            views: doc.viewCount || 0,
            downloads: doc.downloadCount || 0,
            created: doc.createdAt.toLocaleDateString(),
            folder: doc.folderPath || 'N/A'
          }))
        );

        docsSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
        docsSheet.getRow(1).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFf97316' }
        };
      }

      // Generate and return Excel file
      const buffer = await workbook.xlsx.writeBuffer();

      return new NextResponse(buffer, {
        status: 200,
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="document-${template}-report-${new Date().toISOString().split('T')[0]}.xlsx"`,
          'Cache-Control': 'no-cache'
        }
      });
    }

    // For other formats (PDF, CSV), return basic response for now
    return NextResponse.json({
      success: true,
      message: `${format.toUpperCase()} export coming soon. Please use Excel format for now.`,
      documentsIncluded: documents.length
    });

  } catch (error) {
    console.error('Error generating report:', error);
    return NextResponse.json(
      { error: 'Failed to generate report', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}

