/**
 * Provinces / states / regions per country, keyed by the exact `name` in `AFRICAN_COUNTRIES`.
 *
 * **Southern Africa (SADC-oriented):** Angola, Botswana, Comoros, DR Congo, Eswatini, Lesotho,
 * Madagascar, Malawi, Mauritius, Mozambique, Namibia, Seychelles, South Africa, Tanzania, Zambia,
 * and Zimbabwe use **full** primary administrative lists (provinces / regions / districts as applicable).
 *
 * **Still partial (~10 sample divisions, not nationwide):** Algeria, Benin, Burkina Faso, Burundi,
 * Cameroon, Cabo Verde, Central African Republic, Chad, Congo (Republic), Côte d'Ivoire, Djibouti,
 * Egypt, Equatorial Guinea, Eritrea, Ethiopia, Gabon, Gambia, Ghana, Guinea, Guinea-Bissau, Kenya,
 * Liberia, Libya, Mali, Mauritania, Morocco, Niger, Nigeria, Rwanda, São Tomé and Príncipe, Senegal,
 * Sierra Leone, Somalia, South Sudan, Sudan, Togo, Tunisia, Uganda — expand in this file when needed.
 */
export const AFRICAN_REGIONS_BY_COUNTRY: Record<string, string[]> = {
  Algeria: ['Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouira'],
  Angola: [
    'Bengo',
    'Benguela',
    'Bié',
    'Cabinda',
    'Cuando Cubango',
    'Cuanza Norte',
    'Cuanza Sul',
    'Cunene',
    'Huambo',
    'Huíla',
    'Luanda',
    'Lunda Norte',
    'Lunda Sul',
    'Malanje',
    'Moxico',
    'Namibe',
    'Uíge',
    'Zaire',
  ],
  Benin: ['Alibori', 'Atakora', 'Atlantique', 'Borgou', 'Collines', 'Donga', 'Kouffo', 'Littoral', 'Mono', 'Ouémé'],
  Botswana: [
    'Central',
    'Chobe',
    'Francistown',
    'Gaborone',
    'Ghanzi',
    'Jwaneng',
    'Kgalagadi',
    'Kgatleng',
    'Kweneng',
    'Lobatse',
    'North East',
    'North West',
    'Selebi Phikwe',
    'South East',
    'Southern',
    'Sowa Town',
  ],
  'Burkina Faso': ['Bam', 'Banwa', 'Bazèga', 'Bougouriba', 'Boulgou', 'Boulkiemdé', 'Comoé', 'Ganzourgou', 'Gnagna', 'Gourma'],
  Burundi: ['Bubanza', 'Bujumbura Mairie', 'Bujumbura Rural', 'Bururi', 'Cankuzo', 'Cibitoke', 'Gitega', 'Karuzi', 'Kayanza', 'Kirundo'],
  Cameroon: ['Adamawa', 'Centre', 'East', 'Far North', 'Littoral', 'North', 'Northwest', 'South', 'Southwest', 'West'],
  'Cabo Verde': ['Barlavento', 'Sotavento'],
  'Central African Republic': [
    'Bamingui-Bangoran',
    'Bangui',
    'Basse-Kotto',
    'Haute-Kotto',
    'Haut-Mbomou',
    'Kémo',
    'Lobaye',
    'Mambéré-Kadéï',
    'Mbomou',
    'Nana-Grébizi',
  ],
  Chad: ['Batha', 'Borkou', 'Chari-Baguirmi', 'Ennedi Est', 'Ennedi Ouest', 'Guéra', 'Hadjer-Lamis', 'Kanem', 'Lac', 'Logone Occidental'],
  Comoros: ['Anjouan', 'Grande Comore', 'Mohéli'],
  'Congo (Democratic Republic)': [
    'Bas-Uélé',
    'Équateur',
    'Haut-Katanga',
    'Haut-Lomami',
    'Haut-Uélé',
    'Ituri',
    'Kasaï',
    'Kasaï-Central',
    'Kasaï-Oriental',
    'Kinshasa',
    'Kongo Central',
    'Kwango',
    'Kwilu',
    'Lomami',
    'Lualaba',
    'Mai-Ndombe',
    'Maniema',
    'Mongala',
    'Nord-Kivu',
    'Nord-Ubangi',
    'Sankuru',
    'Sud-Kivu',
    'Sud-Ubangi',
    'Tanganyika',
    'Tshopo',
    'Tshuapa',
  ],
  'Congo (Republic)': ['Bouenza', 'Cuvette', 'Cuvette-Ouest', 'Kouilou', 'Lékoumou', 'Likouala', 'Niari', 'Plateaux', 'Pool', 'Sangha'],
  "Côte d'Ivoire": ['Agnéby-Tiassa', 'Bafing', 'Bagoué', 'Béré', 'Bounkani', 'Cavally', 'Folon', 'Gbêkê', 'Gbôklé', 'Gôh'],
  Djibouti: ['Ali Sabieh', 'Arta', 'Dikhil', 'Djibouti', 'Obock', 'Tadjourah'],
  Egypt: ['Alexandria', 'Aswan', 'Asyut', 'Beheira', 'Beni Suef', 'Cairo', 'Dakahlia', 'Damietta', 'Faiyum', 'Gharbia'],
  'Equatorial Guinea': ['Annobón', 'Bioko Norte', 'Bioko Sur', 'Centro Sur', 'Kié-Ntem', 'Litoral', 'Wele-Nzas'],
  Eritrea: ['Anseba', 'Debub', 'Debubawi Keyih Bahri', 'Gash-Barka', 'Maekel', 'Semenawi Keyih Bahri'],
  Eswatini: ['Hhohho', 'Lubombo', 'Manzini', 'Shiselweni'],
  Ethiopia: ['Addis Ababa', 'Afar', 'Amhara', 'Benishangul-Gumuz', 'Dire Dawa', 'Gambela', 'Harari', 'Oromia', 'Sidama', 'Somali'],
  Gabon: ['Estuaire', 'Haut-Ogooué', 'Moyen-Ogooué', 'Ngounié', 'Nyanga', 'Ogooué-Ivindo', 'Ogooué-Lolo', 'Ogooué-Maritime', 'Woleu-Ntem'],
  Gambia: ['Banjul', 'Central River', 'Lower River', 'North Bank', 'Upper River', 'West Coast'],
  Ghana: ['Ashanti', 'Brong-Ahafo', 'Central', 'Eastern', 'Greater Accra', 'Northern', 'Upper East', 'Upper West', 'Volta', 'Western'],
  Guinea: ['Boké', 'Conakry', 'Faranah', 'Kankan', 'Kindia', 'Labé', 'Mamou', 'Nzérékoré'],
  'Guinea-Bissau': ['Bafatá', 'Biombo', 'Bissau', 'Bolama', 'Cacheu', 'Gabú', 'Oio', 'Quinara', 'Tombali'],
  Kenya: ['Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu', 'Garissa', 'Homa Bay', 'Isiolo', 'Kajiado'],
  Lesotho: ['Berea', 'Butha-Buthe', 'Leribe', 'Mafeteng', 'Maseru', "Mohale's Hoek", 'Mokhotlong', "Qacha's Nek", 'Quthing', 'Thaba-Tseka'],
  Liberia: ['Bomi', 'Bong', 'Gbarpolu', 'Grand Bassa', 'Grand Cape Mount', 'Grand Gedeh', 'Grand Kru', 'Lofa', 'Margibi', 'Maryland'],
  Libya: ['Al Wahat', 'Benghazi', 'Derna', 'Ghat', 'Jabal al Akhdar', 'Jabal al Gharbi', 'Jafara', 'Jufra', 'Kufra', 'Marj'],
  Madagascar: [
    'Alaotra-Mangoro',
    "Amoron'i Mania",
    'Analamanga',
    'Analanjirofo',
    'Androy',
    'Anosy',
    'Atsimo-Andrefana',
    'Atsimo-Atsinanana',
    'Atsinanana',
    'Betsiboka',
    'Boeny',
    'Bongolava',
    'Diana',
    'Haute Matsiatra',
    'Ihorombe',
    'Itasy',
    'Melaky',
    'Menabe',
    'Sava',
    'Sofia',
    'Vakinankaratra',
    'Vatovavy-Fitovinany',
  ],
  Malawi: [
    'Balaka',
    'Blantyre',
    'Chikwawa',
    'Chiradzulu',
    'Chitipa',
    'Dedza',
    'Dowa',
    'Karonga',
    'Kasungu',
    'Likoma',
    'Lilongwe',
    'Machinga',
    'Mangochi',
    'Mchinji',
    'Mulanje',
    'Mwanza',
    'Mzimba',
    'Neno',
    'Nkhata Bay',
    'Nkhotakota',
    'Nsanje',
    'Ntcheu',
    'Ntchisi',
    'Phalombe',
    'Rumphi',
    'Salima',
    'Thyolo',
    'Zomba',
  ],
  Mali: ['Bamako', 'Gao', 'Kayes', 'Kidal', 'Koulikoro', 'Mopti', 'Ségou', 'Sikasso', 'Tombouctou'],
  Mauritania: ['Adrar', 'Assaba', 'Brakna', 'Dakhlet Nouadhibou', 'Gorgol', 'Guidimaka', 'Hodh Ech Chargui', 'Hodh El Gharbi', 'Inchiri', 'Nouakchott'],
  Mauritius: ['Black River', 'Flacq', 'Grand Port', 'Moka', 'Pamplemousses', 'Plaines Wilhems', 'Port Louis', 'Rivière du Rempart', 'Savanne'],
  Morocco: [
    'Béni Mellal-Khénifra',
    'Casablanca-Settat',
    'Drâa-Tafilalet',
    'Fès-Meknès',
    'Guelmim-Oued Noun',
    'Laâyoune-Sakia El Hamra',
    'Marrakech-Safi',
    'Oriental',
    'Rabat-Salé-Kénitra',
  ],
  Mozambique: [
    'Cabo Delgado',
    'Gaza',
    'Inhambane',
    'Manica',
    'Maputo',
    'Maputo City',
    'Nampula',
    'Niassa',
    'Sofala',
    'Tete',
    'Zambezia',
  ],
  Namibia: [
    'Erongo',
    'Hardap',
    'Karas',
    'Kavango East',
    'Kavango West',
    'Khomas',
    'Kunene',
    'Ohangwena',
    'Omaheke',
    'Omusati',
    'Oshana',
    'Oshikoto',
    'Otjozondjupa',
    'Zambezi',
  ],
  Niger: ['Agadez', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Tillabéri', 'Zinder'],
  Nigeria: ['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta'],
  Rwanda: ['Eastern', 'Kigali', 'Northern', 'Southern', 'Western'],
  'São Tomé and Príncipe': ['Príncipe', 'São Tomé'],
  Senegal: ['Dakar', 'Diourbel', 'Fatick', 'Kaffrine', 'Kaolack', 'Kédougou', 'Kolda', 'Louga', 'Matam', 'Saint-Louis'],
  Seychelles: [
    'Anse aux Pins',
    'Anse Boileau',
    'Anse Etoile',
    'Anse Royale',
    'Au Cap',
    'Baie Lazare',
    'Baie Sainte Anne',
    'Beau Vallon',
    'Bel Air',
    'Bel Ombre',
    'Cascade',
    'Glacis',
    "Grand'Anse Mahé",
    "Grand'Anse Praslin",
    'La Digue',
    'La Rivière Anglaise',
    'Les Mamelles',
    'Mont Buxton',
    'Mont Fleuri',
    'Plaisance',
    'Pointe La Rue',
    'Port Glaud',
    'Roche Caïman',
    'Saint Louis',
    'Takamaka',
  ],
  'Sierra Leone': ['Eastern', 'Northern', 'Southern', 'Western Area'],
  Somalia: ['Awdal', 'Bakool', 'Banaadir', 'Bari', 'Bay', 'Galguduud', 'Gedo', 'Hiiraan', 'Lower Juba', 'Lower Shabelle'],
  'South Africa': [
    'Eastern Cape',
    'Free State',
    'Gauteng',
    'KwaZulu-Natal',
    'Limpopo',
    'Mpumalanga',
    'Northern Cape',
    'North West',
    'Western Cape',
  ],
  'South Sudan': [
    'Central Equatoria',
    'Eastern Equatoria',
    'Jonglei',
    'Lakes',
    'Northern Bahr el Ghazal',
    'Unity',
    'Upper Nile',
    'Warrap',
    'Western Bahr el Ghazal',
    'Western Equatoria',
  ],
  Sudan: ['Al Jazirah', 'Blue Nile', 'Central Darfur', 'East Darfur', 'Gedaref', 'Kassala', 'Khartoum', 'North Darfur', 'North Kordofan', 'Northern'],
  Tanzania: [
    'Arusha',
    'Dar es Salaam',
    'Dodoma',
    'Geita',
    'Iringa',
    'Kagera',
    'Katavi',
    'Kigoma',
    'Kilimanjaro',
    'Lindi',
    'Manyara',
    'Mara',
    'Mbeya',
    'Mjini Magharibi',
    'Morogoro',
    'Mtwara',
    'Mwanza',
    'Njombe',
    'Pemba North',
    'Pemba South',
    'Pwani',
    'Rukwa',
    'Ruvuma',
    'Shinyanga',
    'Simiyu',
    'Singida',
    'Songwe',
    'Tabora',
    'Tanga',
    'Unguja North',
    'Unguja South',
  ],
  Togo: ['Centrale', 'Kara', 'Maritime', 'Plateaux', 'Savanes'],
  Tunisia: ['Ariana', 'Béja', 'Ben Arous', 'Bizerte', 'Gabès', 'Gafsa', 'Jendouba', 'Kairouan', 'Kasserine', 'Kébili'],
  Uganda: ['Abim', 'Adjumani', 'Agago', 'Alebtong', 'Amolatar', 'Amudat', 'Amuria', 'Amuru', 'Apac', 'Arua'],
  Zambia: ['Central', 'Copperbelt', 'Eastern', 'Luapula', 'Lusaka', 'Muchinga', 'Northern', 'North-Western', 'Southern', 'Western'],
  Zimbabwe: [
    'Bulawayo',
    'Harare',
    'Manicaland',
    'Mashonaland Central',
    'Mashonaland East',
    'Mashonaland West',
    'Masvingo',
    'Matabeleland North',
    'Matabeleland South',
    'Midlands',
  ],
}

export function getRegionsForAfricanCountry(countryName: string): string[] {
  if (!countryName?.trim()) return []
  const regions = AFRICAN_REGIONS_BY_COUNTRY[countryName]
  if (!regions?.length) return []
  return [...regions].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
}

/**
 * Options for a select: regions for the country, plus current value if it is not in the list (legacy bad data on edit).
 */
export function buildEventRegionOptions(countryName: string, currentValue: string): string[] {
  const base = getRegionsForAfricanCountry(countryName)
  if (!countryName?.trim()) return []
  const cv = currentValue?.trim()
  if (cv && !base.includes(cv)) {
    return [cv, ...base]
  }
  return base
}
