name: Test Deployment Setup

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Test AWS credentials
      run: |
        echo "AWS Region: ${{ secrets.AWS_REGION }}"
        echo "NextAuth URL: ${{ secrets.NEXTAUTH_URL }}"
        echo "✅ Secrets are configured"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Test AWS connection
      run: |
        aws sts get-caller-identity
        echo "✅ AWS connection successful"
