'use client'

import React, { useRef } from 'react'
import { useReactToPrint } from 'react-to-print'
import { Button } from '@/components/ui/button'
import { Printer, Loader2 } from 'lucide-react'

interface PrintButtonProps {
  targetId?: string
  targetRef?: React.RefObject<HTMLElement>
  title?: string
  variant?: 'default' | 'outline' | 'ghost'
  size?: 'sm' | 'default' | 'lg'
  className?: string
  onBeforePrint?: () => void
  onAfterPrint?: () => void
}

export function PrintButton({
  targetId,
  targetRef,
  title = 'Print',
  variant = 'outline',
  size = 'default',
  className,
  onBeforePrint,
  onAfterPrint
}: PrintButtonProps) {
  const defaultRef = useRef<HTMLDivElement>(null)
  
  const handlePrint = useReactToPrint({
    contentRef: targetRef || defaultRef,
    documentTitle: title || 'SIRTIS Print'
  })

  return (
    <>
      <Button
        variant={variant}
        size={size}
        className={className}
        onClick={handlePrint}
      >
        <Printer className="h-4 w-4 mr-2" />
        Print
      </Button>

      {/* Hidden print header that will be included in prints */}
      <div ref={defaultRef} className="hidden">
        <div className="print-header">
          <div className="print-logo"></div>
          <div className="print-branding">
            <h1>SAYWHAT</h1>
            <p>SAYWHAT Integrated Real-Time Information System</p>
          </div>
        </div>
        <div id="print-content"></div>
        <div className="print-footer">
          <p>Generated by SIRTIS - SAYWHAT Organization | www.saywhat.org | {new Date().toLocaleString()}</p>
        </div>
      </div>
    </>
  )
}

// Enhanced print component that wraps content with SAYWHAT branding
interface PrintableContentProps {
  children: React.ReactNode
  title?: string
  subtitle?: string
  className?: string
}

export function PrintableContent({ children, title, subtitle, className }: PrintableContentProps) {
  return (
    <div className={className}>
      {/* Print header with SAYWHAT branding */}
      <div className="print-header hidden print:flex print:items-center print:mb-5 print:pb-3 print:border-b-2 print:border-blue-600">
        <div className="print-logo w-15 h-10 bg-blue-600 mr-4 rounded"></div>
        <div className="print-branding">
          <h1 className="text-lg font-bold text-blue-600 m-0">SAYWHAT</h1>
          <p className="text-sm text-gray-600 m-0">SAYWHAT Integrated Real-Time Information System</p>
        </div>
      </div>

      {/* Print title */}
      {title && (
        <div className="print:mb-4">
          <h2 className="text-xl font-semibold text-gray-900">{title}</h2>
          {subtitle && <p className="text-sm text-gray-600 mt-1">{subtitle}</p>}
        </div>
      )}

      {/* Main content */}
      <div className="print-content">
        {children}
      </div>

      {/* Print footer */}
      <div className="print-footer hidden print:block print:fixed print:bottom-0 print:left-0 print:right-0 print:text-center print:text-xs print:text-gray-600 print:p-2 print:border-t print:border-gray-200">
        <p>Generated by SIRTIS - SAYWHAT Organization | www.saywhat.org | {new Date().toLocaleString()}</p>
      </div>
    </div>
  )
}
